services:
  - type: web
    name: travel-guide-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn Backend.app:app
    envVars:
      - key: GEMINI_API_KEY
        sync: false
      - key: MURF_API_KEY
        sync: false
